name: Clone and Copy Files

on:
  push:
    branches:
      - main

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3

      - name: Clone nameless-and-blameless/TAG repository
        run: |
          git clone https://github.com/nameless-and-blameless/TAG.git /tmp/TAG

      - name: Copy files from /wiki to /incoming
        run: |
          mkdir -p incoming
          cp -r /tmp/TAG/wiki/* incoming/

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Copy files from /wiki to /incoming"
          git push
